### ISSUE TITLE
Ground plane

### ISSUE THREAD

**Issue by sweetlilmre** [visrealm/pico-56#11]
Hi there again!

First off not a major issue, so let me start with this:
What a fantastic kit! Super well packaged, labelled and straight forward. My pico-56 is working and I'm amped to get into playing with it. I was lucky enough to to have a mate visiting from Oz that could bring it over for me.

While I was soldering up the board, I had some issues with components connected to the ground plane. I have a good temp controlled iron with a medium chisel tip and good thermal mass, that I usually run at 330C. This wasn't sufficient to create a good joint on certain components e.g. some caps, resistors, a transistor leg, pins on some connectors etc. I ended up having to boost the temp up to about 390-400C with uncomfortably long dwell times.

If I'm the only one with this issue, then tough for me, but I would suggest revising the PCB so that the these components are connected via traces through an island to the ground plane to make assembly easier.

Thanks for the awesome project.

**Comment by visrealm** [comment]
Thanks Peter.

You are the second person to mention this. The other was one of the giveaway winners.

I run a TS-100 with the BC2 tip at 375C. I haven't had the same issues having assembled ~25 of these, but certainly can see that it could be a problem.

If I make another revision of the board, I will certainly look to reduce the ground plane to pad connection thickness.

**Comment by sweetlilmre** [comment]
Thank you, I'll close this.
