### ISSUE TITLE
Q1 (2N4401) question

### ISSUE THREAD

**Issue by g8kuw-tv** [visrealm/pico-56#3]
Hi Troy - I have built a PICO-56, and it's almost working...

Is Q1 in the Pico-56 schematic shown the wrong way around? I can't see how KBD ground will be pulled low when 3v3 is present.

Thanks

Steve

**Comment by visrealm** [comment]
Hi Steve. I think you're right.

However, I just checked a couple of my built examples and confirmed my 2N4401s are indeed oriented as shown in the schematic and it does appear to work fine.

I will update the schematic.

Thanks
Troy

**Comment by g8kuw-tv** [comment]
Thanks Troy!

(I wasn't sure if this was an appropriate place to ask questions.)

**Comment by vslinuxdotnet** [comment]
Hello, 
Sorry about this question but, what is the propose of this transistor to enable GND in keyboard?
The 3v3_en is to enable (default) the PWD of 3.3v, witch is always high, so the transistor is always on.
Regards,
VS

**Comment by visrealm** [comment]
The power and reset buttons are connected to 3.3v_en so the transistor effectively powers off the keyboard when the PICO-56 is "off" (or reset).
