### ISSUE TITLE
Silkscreen / Parts List / Mouser Project not in sync

### ISSUE THREAD

**Issue by lloesche** [visrealm/pico-56#4]
I (admittedly blindly) ordered 5 PCBs using the PCBWay link and 5x the Mouser Project. When assembling everything, I noticed that the silkscreen doesn't even mention 10nf caps, everything is 100nf. But in my Mouser order there were both values delivered. And I believe one of the resistor values was also a different quantity than what I expected based on the values on the board.

Would be good if silkscreen/PCBWay project, Github README, Mouser project, etc. were all in sync.

**Comment by visrealm** [comment]
Hi, the parts you've ordered will work just fine with your PCBs. In later revision of the board, I changed the value of the two 10nF caps to 100nF to reduce part type count. The output/result will be almost identical between the two. For the mouser project, some part counts were increased to take advantage of Mouser's bulk pricing. eg. It's cheaper to order 10 of something than 9.

I will update the BOM to reflect later boards.

**Comment by visrealm** [comment]
I've updated the Mouser project and BOM to reflect the later boards silkscreen. Have also changed *most* of the mouser project quantities to be actual rather than cheaper bulk discounted values except for the 1K resistors I kept at 10 rather than 9 as it's significantly cheaper that way.
