### ISSUE TITLE
Small Nit in release 0.4

### ISSUE THREAD

**Issue by okwatts** [visrealm/pico-56#8]
Looks like circles.bas does not run correctly in version 0.4 If I revert to the same code from release 0.3 it only ever draws the same circle. Did the RND function get affected?

**Comment by okwatts** [comment]
OK my Basic understanding just kicked in and read the Documentation for EhBasic. I needed to alter the initial logic a bit.
15 R=RND(1)
20 I=0
30 R=INT(RND(0)*80)
and because the line 15 resets the random number generator we get the same pattern repeating. If the 1 was replaced in line 15 with a variable we could get different random numbers because the seed has changed. Part of what confused me is that in the source code there is an error in that there are 2 line 20's so the first is overwritten and there is no line 30.
Hope to see more improvements to this code.

**Comment by visrealm** [comment]
Hi. Thanks for pointing out the error in circles.bas. I'll update the .zip file in the release. To:

```
10 DISPLAY 2
20 I = 0: R=RND(1)
30 R = INT(RND(0)*80)
```

I think the core issue depends on the initial state of the RAM. So, in many cases, setting a seed with RND(1) wasn't necessary, but the RAM could be initialized (not explicitly) to a state where RND(0) doesn't generate random numbers without seeding it first. I'll look into that in a future BASIC release.

**Comment by visrealm** [comment]
ROMS package updated with fixed circles.bas
